# first

In [1]:
print("Hello world")

Hello world


In [1]:
import numpy as np

# 1. Generate synthetic data (100 students, scores between 40 and 100)
np.random.seed(42)  # For reproducibility
students = 100
math_scores = np.random.randint(40, 101, students)
science_scores = np.random.randint(40, 101, students)
english_scores = np.random.randint(40, 101, students)

# Combine into a NumPy array
scores = np.array([math_scores, science_scores, english_scores]).T

print("Sample Data (first 5 rows):")
print(scores[:5])

# 2. Calculate basic statistics
mean_scores = np.mean(scores, axis=0)
median_scores = np.median(scores, axis=0)
std_deviation = np.std(scores, axis=0)

print("\n=== Basic Statistics ===")
print(f"Mean: Math={mean_scores[0]:.2f}, Science={mean_scores[1]:.2f}, English={mean_scores[2]:.2f}")
print(f"Median: Math={median_scores[0]}, Science={median_scores[1]}, English={median_scores[2]}")
print(f"Standard Deviation: Math={std_deviation[0]:.2f}, Science={std_deviation[1]:.2f}, English={std_deviation[2]:.2f}")

# 3. Correlation between subjects
correlation_matrix = np.corrcoef(scores.T)
print("\n=== Correlation Matrix ===")
print(correlation_matrix)

# 4. Identify top 5 performers based on average score
average_scores = np.mean(scores, axis=1)
top_students_idx = np.argsort(average_scores)[-5:][::-1]  # Sort descending
print("\nTop 5 Students (Index and Average Score):")
for idx in top_students_idx:
    print(f"Student {idx}: Avg Score = {average_scores[idx]:.2f}")


Sample Data (first 5 rows):
[[78 87 68]
 [91 54 75]
 [68 47 52]
 [54 53 71]
 [82 62 46]]

=== Basic Statistics ===
Mean: Math=70.70, Science=69.29, English=71.27
Median: Math=69.5, Science=70.0, English=71.5
Standard Deviation: Math=18.38, Science=17.22, English=18.33

=== Correlation Matrix ===
[[ 1.         -0.12655036 -0.19500841]
 [-0.12655036  1.          0.12000402]
 [-0.19500841  0.12000402  1.        ]]

Top 5 Students (Index and Average Score):
Student 6: Avg Score = 95.33
Student 45: Avg Score = 88.67
Student 87: Avg Score = 88.33
Student 17: Avg Score = 87.00
Student 82: Avg Score = 84.33
